### PR TITLE
itsybitsy-m4: add spi test

### PR DESCRIPTION
**Pull request by sago35**
This PR adds the SPI test.
I am first adding it to itsybitsy-m4 only, but if it looks OK, other targets can be added with the same code.

### CODE REVIEW

**Comment by deadprogram** [comment]
Finally getting around to look at this. What an excellent idea! I am going to wire up the itsybitsy m4 and try this out shortly.

**Comment by deadprogram** [comment]
Yes, that worked perfectly. I'd like to add this everywhere possible! Looking at the wiring changes needed on other boards now.

**Comment by deadprogram** [comment]
I have added arduino-nano33 spi test based on this.

If you have time to add tests for Arduino Uno and STM32-disco that would be great!

**Comment by sago35** [comment]
@deadprogram 
I do not have an Arduino Uno.
I have stm32f4disco, so I will make this code and check it.

**Pull request merged**
